name: Unit Tests1
on:
  push:
    branches:
      - rhoai
      - incubation
      - main
  pull_request:
    paths:
      - 'internal/**'
      - 'pkg/**'
      - 'cmd/main.go'
      - 'tests/integration/**'


jobs:
  unit-test:
    name: Run tests and collect coverage on tests/integration
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Run Unit Tests
        env:
          TEST_SRC: ./tests/integration/...
        run: make unit-test

      - name: Upload results to Codecov
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: codecov/codecov-action@v5.4.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false